// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWStructuredBuffer<float4x4> grassTransforms;
int dimensions;

float4x4 QuatToMatrix(float4 q)
{
    float4x4 rotMat = float4x4
    (
        float4(1 - 2 * q.y * q.y - 2 * q.z * q.z, 2 * q.x * q.y + 2 * q.w * q.z, 2 * q.x * q.z - 2 * q.w * q.y, 0),
        float4(2 * q.x * q.y - 2 * q.w * q.z, 1 - 2 * q.x * q.x - 2 * q.z * q.z, 2 * q.y * q.z + 2 * q.w * q.x, 0),
        float4(2 * q.x * q.z + 2 * q.w * q.y, 2 * q.y * q.z - 2 * q.w * q.x, 1 - 2 * q.x * q.x - 2 * q.y * q.y, 0),
        float4(0, 0, 0, 1)
    );
    return rotMat;
}

float4x4 MakeTRSMatrix(float3 pos, float4 rotQuat, float3 scale)
{
    float4x4 rotPart = QuatToMatrix(rotQuat);
    float4x4 trPart = float4x4(float4(scale.x, 0, 0, pos.x), float4(0, scale.y, 0, pos.y), float4(0, 0, scale.z, pos.z), float4(0, 0, 0, 1));
    return mul(trPart, transpose(rotPart));
}

[numthreads(32,1,32)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4x4 trs = MakeTRSMatrix(float3(id.x * 2, 0, id.z * 2), float4(0, 0, 0.7071068, 0.7071068), float3(1,1,1));
    grassTransforms[id.x * 32 + id.z] = trs;
}
